Set-Alias -Name 'exists' -Value 'Test-Path'
Set-Alias -Name 'goto' -Value 'Set-Location'
Set-Alias -Name 'exity' -Value 'exit'
Set-Alias -Name 'ci' -Value 'code-insiders.cmd'
Set-Alias -Name 'docs' -Value 'documents'
